In [2675]:
import numpy as np

# **Main Assignment 2 Numpy ja Pandas**

-----------------------

## **Numpy Section**

----

## 1.1

In [2676]:
eka = np.array([1, 2, 5, 7, 8])

In [2677]:
eka.shape

(5,)

Shape kertoo kuinka monta asiaa arrayssa on.

In [2678]:
eka.dtype

dtype('int64')

Dtype kertoo minkälaista dataa on sisällä.

In [2679]:
print(eka[1])

2


-------

## 1.2

In [2680]:
matrix = np.random.randint(low=1, high=11, size=(10,10))

Low kertoo pienimmän luvun ja high isoimman luvun joka voi löytyä (10 tässä tapauksessa) ja size tekee matriisin koon.

In [2681]:
print(matrix)

[[ 6  9  8 10  3  4  3  7  6  4]
 [ 2  8  1  2  7 10  6  9 10  3]
 [ 8  1  3  4  6  9  3  8  5 10]
 [ 8  8  7  7  3  8  8  4  3  4]
 [10  1 10 10  4  3  8  4  7  3]
 [ 4  9  3 10  2  3 10 10  9  4]
 [10  1  2  9  9  9  9  3  6  2]
 [ 1  7  9  5  9  5  5  6  9  7]
 [ 4  8 10  3  6  8  7  5  8  9]
 [ 5  3  7  8  3  8  6 10  2  9]]


In [2682]:
matrix.shape

(10, 10)

In [2683]:
matrix.dtype

dtype('int32')

---------

## 1.3

In [2684]:
print(np.mean(matrix))

6.11


Mean antaa keskiarvon matriisista.

In [2685]:
print(matrix.sum())

611


Sum antaa matriisin lukujen summan.

In [2686]:
print(matrix.min())

1


Min antaa matriisin pienimmän luvun.

In [2687]:
print(matrix.max())

10


Max antaa matriisin isoimman luvun.

--------

## 1.4

Tässä kohdassa "[0]" ottaa matriisista ensimmäisen rivin. Loput ovat samoja laskelmia kuin yllä.

In [2688]:
print(np.mean(matrix[0]))

6.0


In [2689]:
print(matrix[0].sum())

60


In [2690]:
print(matrix[0].min())

3


In [2691]:
print(matrix[0].max())

10


--------

## 1.5

Low nopan pienin luku, high nopan isoin luku ("20") ja size nopan heittojen määrä.

In [2692]:
d20_roolipelinoppa = np.random.randint(low=1, high=21, size=100)
print(d20_roolipelinoppa)

[20  6  7  2  9 19  4 11  1  2  7  6 12  2  5 18  4  7 10 18  2 19  2  6
  4  7 11 12  4 13 20 15  6  1  2  2  7  3  4 15 14  9  9  9 20  3 12  4
  8 15  5  5  5 10 13 10 11 18 18 15  5 11 11 14 20 19 10 13 11 19 12 20
 11  2 16  3 19 16 18 11  1  6  7 17 17 14  3  2  5 18  3 11 17 13 14 11
 18  9 20  6]


Bincount() laskee lukujen 1-20 määrät sadan heiton aikana.

In [2693]:
määrät = np.bincount(d20_roolipelinoppa)
print(määrät)

[ 0  3  9  5  6  6  6  6  1  5  4 10  4  4  4  4  2  3  7  5  6]


Seuraava kohta kertoo printillä hieman selvemmin lukujen määrät.

In [2694]:
for arvo in range (1, 21):
    print(f"Numero {arvo} toistuu {määrät[arvo]} kertaa")

Numero 1 toistuu 3 kertaa
Numero 2 toistuu 9 kertaa
Numero 3 toistuu 5 kertaa
Numero 4 toistuu 6 kertaa
Numero 5 toistuu 6 kertaa
Numero 6 toistuu 6 kertaa
Numero 7 toistuu 6 kertaa
Numero 8 toistuu 1 kertaa
Numero 9 toistuu 5 kertaa
Numero 10 toistuu 4 kertaa
Numero 11 toistuu 10 kertaa
Numero 12 toistuu 4 kertaa
Numero 13 toistuu 4 kertaa
Numero 14 toistuu 4 kertaa
Numero 15 toistuu 4 kertaa
Numero 16 toistuu 2 kertaa
Numero 17 toistuu 3 kertaa
Numero 18 toistuu 7 kertaa
Numero 19 toistuu 5 kertaa
Numero 20 toistuu 6 kertaa


----------------

# **Pandas Section**

------------------------

## 2.1

-------------------

## 2.2

------------------------

## 2.3

---------------------