In [2795]:
import numpy as np

# **Main Assignment 2 Numpy ja Pandas**

-----------------------

## **Numpy Section**

----

### **1.1**

In [2796]:
eka = np.array([1, 2, 5, 7, 8])

In [2797]:
eka.shape

(5,)

Shape kertoo kuinka monta asiaa arrayssa on.

In [2798]:
eka.dtype

dtype('int64')

Dtype kertoo minkälaista dataa on sisällä.

In [2799]:
print(eka[1])

2


-------

### **1.2**

In [2800]:
matrix = np.random.randint(low=1, high=11, size=(10,10))

Low kertoo pienimmän luvun ja high isoimman luvun joka voi löytyä (10 tässä tapauksessa) ja size tekee matriisin koon.

In [2801]:
print(matrix)

[[ 1  6  7  7  3  5  1  5 10  3]
 [ 8  8  2  4  7  8  5  2  9  8]
 [10  4  7  3  6  2  1  7  3  7]
 [ 9  6  8  7  2  3  2  8  3  7]
 [ 5  4 10  3  1  1  1  5  1  5]
 [ 4 10  8  9  8  8  9 10  4  6]
 [ 3  9  1  2  2 10  6  5  1  5]
 [ 5  7  7 10  6  2  6  8  5  6]
 [ 6  2  7  6  9  7  8  9  1  4]
 [ 5  3 10  9  1  4  9  7  6  1]]


In [2802]:
matrix.shape

(10, 10)

In [2803]:
matrix.dtype

dtype('int32')

---------

### **1.3**

In [2804]:
print(np.mean(matrix))

5.46


Mean antaa keskiarvon matriisista.

In [2805]:
print(matrix.sum())

546


Sum antaa matriisin lukujen summan.

In [2806]:
print(matrix.min())

1


Min antaa matriisin pienimmän luvun.

In [2807]:
print(matrix.max())

10


Max antaa matriisin isoimman luvun.

--------

### **1.4**

Tässä kohdassa "[0]" ottaa matriisista ensimmäisen rivin. Loput ovat samoja laskelmia kuin yllä.

In [2808]:
print(np.mean(matrix[0]))

4.8


In [2809]:
print(matrix[0].sum())

48


In [2810]:
print(matrix[0].min())

1


In [2811]:
print(matrix[0].max())

10


--------

### **1.5**

Low nopan pienin luku, high nopan isoin luku ("20") ja size nopan heittojen määrä.

In [2812]:
d20_roolipelinoppa = np.random.randint(low=1, high=21, size=100)
print(d20_roolipelinoppa)

[18  6 10 13 10 13 17 11 16 20 17 16  1  4  7 16 14  3  6 17  3 10  1 14
 18 12  3 15 11  1  1 10  3 13 14  6 16 18  7 14 18 17 13  7  5  6  3  9
 19 13 17 13  8 17 14 11 18  5 20 13 11  5 11 19 16  7  4 14 12  1 12 11
 18 13 13  8 14  4  5  6  7 20 13 12  8 20 14  8 11  2  7  5  4  4 14 13
 12  5 20  7]


Bincount() laskee lukujen 1-20 määrät sadan heiton aikana.

In [2813]:
määrät = np.bincount(d20_roolipelinoppa)
print(määrät)

[ 0  5  1  5  5  6  5  7  4  1  4  7  5 11  9  1  5  6  6  2  5]


Seuraava kohta kertoo printillä hieman selvemmin lukujen määrät.

In [2814]:
for arvo in range (1, 21):
    print(f"Luku {arvo} toistuu {määrät[arvo]} kertaa")

Luku 1 toistuu 5 kertaa
Luku 2 toistuu 1 kertaa
Luku 3 toistuu 5 kertaa
Luku 4 toistuu 5 kertaa
Luku 5 toistuu 6 kertaa
Luku 6 toistuu 5 kertaa
Luku 7 toistuu 7 kertaa
Luku 8 toistuu 4 kertaa
Luku 9 toistuu 1 kertaa
Luku 10 toistuu 4 kertaa
Luku 11 toistuu 7 kertaa
Luku 12 toistuu 5 kertaa
Luku 13 toistuu 11 kertaa
Luku 14 toistuu 9 kertaa
Luku 15 toistuu 1 kertaa
Luku 16 toistuu 5 kertaa
Luku 17 toistuu 6 kertaa
Luku 18 toistuu 6 kertaa
Luku 19 toistuu 2 kertaa
Luku 20 toistuu 5 kertaa


----------------

## **Pandas Section**

------------------------

### **2.1**

-------------------

### **2.2**

------------------------

### **2.3**

---------------------